# Generated by Django 2.2.6 on 2019-11-07 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_delete_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Booking',
        ),
    ]
