# Generated by Django 2.2.6 on 2019-11-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20191107_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.CharField(default='ac', max_length=6),
        ),
    ]
