# Generated by Django 2.2.6 on 2019-11-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_delete_booking'),
        ('hotels', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomType', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField(default=0)),
                ('BedOption', models.CharField(max_length=255)),
                ('Price', models.IntegerField(default=0)),
                ('TotalRooms', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Hotels')),
            ],
        ),
    ]
