# Generated by Django 2.2.6 on 2019-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20191108_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(default=0, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='room',
            name='pools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='smart_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
