# Generated by Django 2.2.6 on 2019-11-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_room_ac'),
    ]

    operations = [


    ]
