# Generated by Django 2.2.6 on 2019-11-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20191108_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
    ]
