# Generated by Django 2.2.6 on 2019-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_remove_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guestFirstName',
            field=models.CharField(default='NONE', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='guestLastName',
            field=models.CharField(default='NONE', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='roomtype',
            field=models.CharField(default='standard', max_length=255),
        ),
    ]
