# Generated by Django 2.2.6 on 2019-10-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=15, null=True)),
                ('mob_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('charges', models.IntegerField(blank=True, null=True)),
                ('mob_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guide',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('ac_rooms', models.IntegerField(default=0)),
                ('ac_price', models.IntegerField(default=0)),
                ('non_ac_rooms', models.IntegerField(default=0)),
                ('non_ac_price', models.IntegerField(default=0)),
                ('photo', models.ImageField(default=0, upload_to='pics')),
            ],
            options={
                'db_table': 'hotels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Guide')),
            ],
            options={
                'db_table': 'tourist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField(default=0)),
                ('date', models.DateField(default=0)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Driver')),
            ],
            options={
                'db_table': 'pickup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=30)),
                ('mob_no', models.IntegerField(blank=True, null=True)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Hotels')),
            ],
            options={
                'db_table': 'guests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('cust_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=10)),
                ('check_in', models.DateTimeField(default=0)),
                ('check_out', models.DateTimeField(default=0)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Hotels')),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
        ),
    ]
