# Generated by Django 2.2.6 on 2019-11-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191104_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='pools',
            field=models.BooleanField(default=False),
        ),
    ]
