# Generated by Django 2.2.6 on 2019-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_hotels_pools'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='description',
            field=models.TextField(default='hotel'),
        ),
    ]
