# Generated by Django 2.2.6 on 2019-11-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='ac_price',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='ac_rooms',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='non_ac_price',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='non_ac_rooms',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='pools',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='smart_tv',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='wifi',
        ),
    ]
