# Generated by Django 2.2.6 on 2019-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_hotels_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
